---

server :
  port: 8888

spring:
#  profiles:
#    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pratikaambani/spring-cloud-config
          #for private gitlab repos
          #username:
          #password: